sinonjs/referee

package.json
Used negate expressions in `package.json` files entry, although it goes
against recommendation below, because that's the only thing that
worked. Read the github references below for details.
> "The consequences are undefined" if you try to negate any of the files
> entries (that is, "!foo.js"). Please don't. Use .npmignore.
https://github.com/npm/npm/wiki/Files-and-Ignores#details
```text
.
├── LICENSE
├── README.md
├── docs
│   └── index.md
├── lib
│   ├── expect.js
│   └── referee.js
└── package.json
```
This uses [`tree`](https://en.wikipedia.org/wiki/Tree_(Unix)), on macOS install it using `brew install tree`
1. `npm install`
1. `npm pack`
1. Unpack the `sinonjs-referee-2.0.0.tgz` just created
1. `cd package`
1. `tree .`
1. Observe that you see the same as the …
=> Add files directive to package.json to speed up installs

.eslintignore, .eslintrc.yaml, .gitignore, lib/expect.js, lib/referee.js, package-lock.json, package.json, rollup.config.js
This PR removes the UMD wrapper around the source files, and instead provides a `dist/` folder with a UMD wrapped bundled version of `referee`.
Additionally, it removes `lodash` dependency, in favour of using native methods, polyfills and using standalone lodash methods. This should make the library slightly faster to install, and in modern runtimes also faster to use.
Reviewers are advised to read commits in turn, instead of all at once.
3. `npm run prepublish` (this runs `build`)
4. Observe that there is a new `dist/` folder, with a UMD wrapped version
5. If you're still here, try using the `dist` version in a project
=> Remove UMD wrapper and (most of) lodash

package-lock.json, package.json
This PR updates dependencies to stop using known insecure packages from npm
1. Check out `master`
1. `npm install`
1. `npm audit`
1. Observe several warnings
1. `npm install`
1. `npm audit`
1. Observe there are no warnings
=> Update insecure packages as reported by npm audit

lib/referee.js
Fix #23 by replacing dynamic requires with boring repeating code.
It seems proxyquireify that is used when running commonjs code in a browser has problems with this way of importing code. I tried making the code a bit more boring (easier to parse) and that worked.
2. `npm link`
3. Go to the `sinon` folder
4. In the `sinon` folder, do `npm link @sinonjs/referee` to use the local version
5. `npm run test-headless`
=> Fix #23: replace dynamic requires with boring repeating calls

lib/assertions/is-range-error.js, lib/assertions/is-reg-exp.js, lib/assertions/is-syntax-error.js, lib/referee.test.js, lib/test-helper.js
The test-helper `msg` test cases wheren't executed anymore. I didn't care to bisect into why, I assume during the test framework migration this got left behind.
Unfortunately, a bunch of test cases where copy-pasted afterwards without checking whether they'd actually go red under any circumstance.
3. `npm test`
=> Fix message tests

docs/index.md, lib/assertions/json.js, lib/assertions/match-json.js, lib/expect.test.js, lib/referee.js, lib/referee.test.js
This allows to compare a JSON string with an object, making it easier to read in the tests, and isn't sensitive to the ordering of properties.
I often find myself comparing JSON strings with `assert.equals`, or parsing a JSON string, fish out a property and assert the value. Sometimes a small code change results in a re-ordering of properties in the JSON serialization and a bunch of tests fail, even though the actual properties havn't changed.
The two new assertions allow to directly compare a JSON string with an object and provide good exception messages on parse errors or assertion failures:
- `assert.json(jsonString, value)` parses `jsonString` and compares it with `value`
- `assert.matchJson(jsonString, value` parses `jsonString` and matches it with `value` using the `referee.match` …
=> assert.json and assert.matchJson

docs/index.md, lib/assertions/is-date.js, lib/expect.test.js, lib/referee.js, lib/referee.test.js
While converting a test suite to referee I noticed that there is no `isDate` assertion while other built in types can be asserted this way (e.g. `isRegExp`, `isError`, ...).
3. `npm t`
=> Add isDate assertion

lib/expect.js, package-lock.json, package.json
If https://github.com/sinonjs/samsam/pull/33 is merged, we should switch to using the same polyfill in `referee`.
---
`samsam` needs a polyfill for `Array.prototype.from`. Replacing
`array.from` with `array-from` means that end users will only have to
download ony polyfill, not two
3. `npm test`
=> Replace array.from with array-from

.travis.yml, lib/assertions/is-function.js
The toString representation of functions has changed slightly between Node 8 and Node 10. Node 10 retains the original whitespace between the function keyword and the opening braces while Node 8 always inserts a blank.
These differences caused `refute.isFunction` tests to fail on Node 10 while they passed on Node 8.
| Command | Node 6 & 8 | Node 10 |
|---|---|---|
| `node -p 'String(function () {})'` | `function () {}` | `function () {}` |
| `node -p 'String(function() {})'` | `function () {}` | `function() {}` |
3. `npm test`
=> Fix isFunction failure message differences

lib/assert-exception-unexpected-exception.test.js, lib/assertions/contains.js, lib/assertions/equals.js, lib/referee.js, lib/referee.test.js, lib/test-helper.js, package-lock.json, package.json
The current formatting algorithm is literally `String(value)` which is not very helpful most of the time.
This change makes use of `@sinonjs/formatio` instead and replaces the custom multiline formatting logic with a simple newline escape helper. A follow up PR will add `actual` and `expected` properties onto Referee exceptions which allows the test runners to show diffs depending on the reporter in use (see discussion on https://github.com/sinonjs/referee/issues/20).
Note that the way formatio is used is very similar to the sinon core format helper. We might want to unify the logic by having a common formatter instance in `@sinonjs/commons`.
=> Use @sinonjs/formatio to format values

demo/diff.test.js, lib/assertions/equals.js, lib/assertions/is-array-buffer.js, lib/assertions/is-array-like.js, lib/assertions/is-array.js, lib/assertions/is-boolean.js, lib/assertions/is-data-view.js, lib/assertions/is-error.js, lib/assertions/is-eval-error.js, lib/assertions/is-float-32-array.js, lib/assertions/is-float-64-array.js, lib/assertions/is-function.js, lib/assertions/is-infinity.js, lib/assertions/is-nan.js, lib/assertions/is-null.js, lib/assertions/is-number.js, lib/assertions/is-object.js, lib/assertions/is-string.js, lib/assertions/is-symbol.js, lib/assertions/json.js, lib/assertions/keys.js, lib/assertions/match-json.js, lib/referee.js, lib/referee.test.js, lib/test-helper.js, package.json
~~Do not merge until 34 is merged and this branch has been rebased against master. This change currently also contains the commit from 34.~~
This applies parts of the Node AssertionError convention to the AssertionError thrown by Referee (see https://nodejs.org/api/assert.html#assert_new_assert_assertionerror_options). The exposed `actual` and `expected` properties allow test runners to renders diffs. The `code` property is always set to "ERR_ASSERTION" and `operator` is set to the type and name of the Referee assertion or refutation.
Refutation do not expose `actual` and `expected` values because the values are usually equal to each other.
=> Set code, actual and expected properties on errors

demo/diff.test.js, lib/actual-for-match.js, lib/assertions/match-json.js, lib/assertions/match.js, lib/referee.test.js
When asserting plain objects using match or matchJson, set the "actual"
object to an excerpt only containing the properties specified by the
matcher. If the original "actual" object is used, the diff produced by
test runners shows all properties that are not defined in the matcher as
missing. With this change, only properties that are actually compared
are shown.
3. `npm test`
Also the `matchJson` demo was enhanced. Run it with `npm run demo`.
=> Reduce actual for match and matchJson

lib/assertions/equals.js, lib/assertions/json.js, lib/assertions/match.js, lib/assertions/same.js, package-lock.json, package.json
samsam is deprecated and doesn't get updated anymore
3. `npm test`
=> Prefer @sinonjs/samsam

package-lock.json, package.json
Upgrade to the latest `@sinonjs/formatio`, which contains the latest `@sinonjs/samsam`
3. <your-steps-here>
=> Upgrade formatio

docs/index.md
I really like the docs, they  are compact and have great examples! Still I miss a tiny but common bit:
* A small note on how to install `referee`.
* Furthermore I think the block about the _SinonJS integration_ seems a bit lost between _Events_ and _Expectation_ somehow.
Add a block on how to install `referee` via npm as a dev dependency on top of the docs.  Also move the note about the sinonjs integration below that blog as a third level block.
I don't know if this makes sense or if this was spared out on purpose. Any thoughts?
1. Check the [`referee` docs](https://sinonjs.github.io/referee/)
2. Compare:
=> refactor(docs): add install note

docs/index.md
This PR does:
* highlight **referee** everywhere
* fix some markdown issues
* fix custom html to style code blocks properly
2. `mkdocs serve -f mkdocs.yml`
3. go to localhost:8000
=> fix(docs): style changes

docs/index.md
This PR improves the documentation by adding a few headers and re-organising the links in the overview, hopefully making it easier for readers to determine if there is a built-in assertion for what they want to do.
=> Add some more structure to documentation

docs/index.md, lib/assertions/has-arity.js, lib/assertions/has-arity.test.js, lib/referee.js, lib/referee.test.js
This PR is branched from #41, which should be merged before reviewing this.
The PR adds a new assertion `hasArity`.
3. `npm test`
=> Add has arity

.travis.yml, docs/index.md, lib/assert.test.js, lib/count-assertion.js, lib/create-add.js, lib/create-assert.js, lib/create-count-assertion.js, lib/create-refute.js, lib/create-reset-count.js, lib/create-verify.js, lib/custom-assertions.test.js, lib/define-assertion.js, lib/expect.test.js, lib/referee.js, lib/referee.test.js, lib/reset-count.test.js, lib/test-helper/index.js, lib/verify.test.js
Ref discussion in #47
* Improve `referee.count` so that it can't be written to directly.
* Add `referee.verify()` which will verify that count is not zero, and optionally is expected value
* Add `referee.resetCount()`, which predictably resets the count to zero
3. `npm test`
=> Add .verify() and .resetCount()

lib/add.test.js, lib/assert.test.js, lib/create-add.js, lib/create-assert.js, lib/create-refute.js, lib/interpolate-properties.js, lib/refute.test.js
This PR improves test coverage by adding missing tests for a few functions.
```text
-------------|----------|----------|----------|----------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |
-------------|----------|----------|----------|----------|
All files    |    96.74 |    90.71 |    98.91 |    96.74 |
```
```text
-------------|----------|----------|----------|----------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |
-------------|----------|----------|----------|----------|
All files    |    98.69 |    97.18 |      100 |    98.69 |
```
3. `npm test`
=> Improve coverage

lib/define-assertion.js
This PR tidies up `define-assertion.js` slightly by removing extraneous internal arguments and not passing `referee.fail` twice to `assertArgNum` (which would just use the equivalent of `var fail = referee.fail || referee.fail`).
3. `npm test`
=> Refactor define assertion

docs/index.md, lib/assertions/rejects.js, lib/assertions/rejects.test.js, lib/assertions/resolves.js, lib/assertions/resolves.test.js, lib/create-async-assertion.js, lib/create-async-assertion.test.js, lib/define-assertion.js, lib/referee.js
Copy of #44 because I accidentally closed with `git push --force` :man_facepalming:  
This is a first attempt for #27 
Adds a `resolves` assertion to **referee**, that uses `samsam`'s `identical` method to check if a promise resolves to an expected value. The assertion returns a Promise which can be passed to the test runner to know that this is an async method.
* If both values are identical the returned Promise resolves.
* If both values are different the returned Promise rejects and fails.
* If the given Promise/async method does not resolve, the returned Promise will reject.
* If the given input is not a Promise/async method the, the returned Promise will reject
3. `npm test`
=>  feat(assertion) add resolves/rejects assertions

lib/assertions/is-array-buffer.test.js
Use node's assert and plain Mocha
This is part of a bigger effort to remove `test-helper.js` and just have plain tests using Mocha, which will make `referee` a lot easier to contribute to.
2. `npm ci`
3. `npm test`
=> Rewrite tests for isArrayBuffer

lib/assertions/resolves.test.js, package.json
This PR changes the default reporter to be "dot", which makes it easier to spot when there is unexpected output, like misconfigured tests. Also, fix the misconfigured test.
1. `git checkout 248110a4ec470f83859bd03c94b6f6c362e0ab59` (current `master`)
1. `npm ci`
1. `npm test | grep "UnhandledPromiseRejectionWarning"`
1. Observe that there's output like the example below
```text
(node:20945) UnhandledPromiseRejectionWarning: AssertionError: [refute.resolves] test is identical to test
at Object.fail (/Users/morgan/code/sinonjs/referee/lib/create-fail.js:5:25)
at Object.fail (/Users/morgan/code/sinonjs/referee/lib/define-assertion.js:58:25)
at /Users/morgan/code/sinonjs/referee/lib/create-async-assertion.js:24:18
at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20945) …
```
=> Use dot reporter and fix misconfigured test

lib/assertions/is-boolean.test.js
This is branched from #62, which should be merged first
2. `npm ci`
3. `npm test`
=> Rewrite tests for isBoolean

lib/assertions/is-data-view.test.js
=> Rewrite isDataView test

lib/assertions/is-date.test.js, package.json
Update `npm test` to run tests in UTC timezone, so that date based tests
are reproducible, no matter where in the world the test are run.
2. `npm ci`
3. `npm test`
=> Rewrite tests for isDate

lib/assertions/is-error.test.js
=> Rewrite tests for isError

lib/assertions/is-false.test.js
=> Rewrite tests for isFalse

lib/assertions/is-eval-error.test.js
=> Rewrite tests for isEvalError

lib/assertions/is-float-32-array.test.js, lib/assertions/is-float-64-array.test.js
=> Rewrite tests for isFloat32Array and isFloat64Array

.github/CONTRIBUTING.md, .gitignore, .travis.yml, README.md, lib/create-add.js, lib/define-assertion.js, lib/expect.js, lib/expect.test.js, package.json
This PR takes test coverage to 100% and puts in measures to ensure that it will stay at 100%.
The `test-check-coverage` task is run on `pre-commit` and by Travis.
This PR contains a **breaking** change ... we already have a number of breaking changes in `master`, so the next release needs to be a **major**.
1. `npm install`
1. Make changes to a file that would not be covered by an existing test, ex: `if (false) { return; }`
1. Try to commit the changes
1. Observe that the pre-commit hook prevents your commit
=> Coverage 💯

lib/assertions/is-function.test.js
=> Rewrite tests for isFunction

docs/index.md, lib/assertions/is-infinity.test.js, lib/assertions/is-negative-infinity.js, lib/assertions/is-negative-infinity.test.js, lib/referee.js
**Bonus commit:** Add `isNegativeInfinity`
2. `npm ci`
3. `npm test`
=> Rewrite tests for isInfinity

package.json
This ensures that all source files are considered when measuring
coverage, even those without any test coverage.
Excludes `rollup.config.js`
3. Try adding a file that ins't covered by tests
1. `npm run test-check-coverage`
1. Observe that the command fails
=> Configure nyc to include all files

lib/assertions/exception.js, lib/assertions/match.test.js, package-lock.json, package.json
__BREAKING:__ Upgrade samsam to v3 with slightly changed `deepEqual` and `match` semantics.
A small change in the verification logic for exceptions was required to reduce the "breakingness" of this upgrade.
What we will gain from samsam 3 is a unified approach to using custom and built in matches. With this change, the Sinon matchers have moved to samsam and can be used in referee within `assert.equals`.
3. `npm t`
=> Upgrade samsam to v3

docs/index.md, lib/match.test.js, lib/referee.js, lib/referee.test.js, package.json
Since we now integrated with samsam 3, I'd like to expose a `match` function that can be used with `assert.equals` and `refute.equals`.
This change adds API tests, an integration test, and a small note in the documentation.
Obviously, this should be documented a lot better. I'm wondering if we should put the docs in samsam and refer to them here, or whether it should be documented in referee 🤔 
I also had to add two more excludes to the nyc config, or I wouldn't be able to commit anything 😆 
3. `npm t`
=> Expose match

lib/assertions/is-int-32-array.test.js
=> Rewrite tests for isInt32Array

lib/assertions/is-int-8-array.test.js
=> Rewrite tests for isInt8Array

lib/assertions/is-intl-collator.test.js, lib/assertions/is-intl-date-time-format.test.js, lib/assertions/is-intl-number-format.test.js, lib/assertions/is-map.test.js, lib/assertions/is-nan.test.js, lib/assertions/is-null.test.js
=> Rewrite even more tests

lib/assertions/is-number.test.js, lib/assertions/is-object.test.js, lib/assertions/is-promise.test.js
=> Rewrite more tests

lib/format.js, lib/format.test.js, lib/referee.js, lib/referee.test.js
This is an alternative to #82. Instead of exposing the formatter, this introduces `setFormatter` in exactly the same way as Sinon does. With this change, `referee-sinon` can create its own formatter and inject it into Sinon and Referee (inversion of control FTW).
3. `npm t`
=> Add setFormatter from Sinon

lib/assertions/is-range-error.test.js, lib/assertions/is-reference-error.test.js, lib/assertions/is-syntax-error.test.js, lib/assertions/is-type-error.test.js, lib/assertions/is-uri-error.test.js
=> Refactor is*Error tests

lib/custom-assertions.test.js, lib/define-assertion.js
This fixes an issue in IE 11 where `Promise` is not defined (see failing tests in https://github.com/sinonjs/samsam/pull/62).
Feature detect Promise support.
3. `npm t`
=> Feature detect Promise for old IE

lib/assertions/tag-name.test.js
Remove test helper from tag name file
Also I have removed the refute tests, as doing the test then the same with a refute feels a bit pointless, I don't feel it would improve coverage but I am open to be told otherwise, I did some searching on the web to see if there is a reason to follow such a pattern.
=> Remove test helper from tag name

lib/assertions/defined.js, lib/assertions/is-undefined.js, lib/assertions/is-undefined.test.js, lib/expect.test.js, lib/referee.js, lib/test-helper/index.js, package-lock.json, package.json
This PR introduces an assertion called `isUndefined` that passes when the given value is `undefined`. This also deprecates the `defined` assertion
See #87 #89 
3. `npm run test`
=> Introduce isUndefined, deprecate defined

lib/assertions/equals.test.js, package-lock.json, package.json
This updates samsam to `v3.3.0` to [add symbol property support](https://github.com/sinonjs/samsam/pull/64) and fixes the related test cases.
3. `npm t`
=> Update @sinonjs/samsam to v3.3.0 for symbol property support

lib/assertions/equals.js, lib/assertions/equals.test.js
This is up for discussion. It's a breaking change and I'm not 100% sure about it.
I noticed that `assert.equals(foo.property, bar.property)` would pass if both properties are not defined, although it's unlikely that this meets my expectation.
This change throws if the expectation is `undefined` with a message recommending the use of `assert.defined` or `refute.defined` instead.
What are your thoughts on this? If we want to try to protect against cases like these, are there other assertions that should be changed as well?
3. `npm t`
=> Fail when passing undefined as the expectation for equals

lib/assertions/near.test.js
Remove test helper from spec to lower barrier of entry to the codebase
=> Get rid of test helper from near.spec.js

lib/assert-arg-num.test.js
This was only implicitly covered by other tests. As they change when we
rewrite those to not use `testHelper` but plain Mocha + node assert,
then coverage for this helper drops below the threshold.
Ultimately, I'd like to rewrite this, so that it doesn't have two arguments for failing, but that will touch a lot of files, so I'll do that in a later PR.
2. `npm ci`
3. `npm test`
=> Add tests for internal helper assertArgNum

lib/assertions/has-prototype.test.js, lib/define-assertion.js
This PR rewrites the tests for `hasPrototype`
While working on this, I discovered the unnecessary conditional in `defineAssertion`, so the first commit is for that.
2. `npm ci`
3. `npm test`
=> Rewrite tests for hasPrototype

lib/assert-arg-num.js, lib/assert-arg-num.test.js, lib/assert.test.js, lib/assertions/class-name.test.js, lib/assertions/exception.test.js, lib/assertions/has-prototype.test.js, lib/assertions/is-true.test.js, lib/assertions/near.test.js, lib/refute.test.js
Remove `customFailArg`. It's only being used in tests.
3. `npm test`
=> Refactor assertArgNum to remove customFail arg

.circleci/config.yml
This PR improves the CircleCI setup
* Stop testing in node 6
* Start testing in node 12
* Install dependencies once
* Only run the linter once
* Only measure coverage once
* Prevent husky from installing git hooks
1. If CircleCI has approved the PR, then it's good :)
=> Improve CircleICI setup

lib/assertions/match-json.js, lib/custom-assertions.test.js, lib/define-assertion.js
The `values` function should only be invoked if a failure occurred. Currently this function is invoked for passing tests as well.
I removed a superfluous conditional in `match-json.js` which was highlighted by the coverage report, now that the function isn't invoked on passing tests anymore.
3. `npm t`
=> Exception in values

lib/assertions/rejects.js, lib/assertions/resolves.js
This PR adds missing expecation properties for `resolves` and `rejects` assertions.
Improve support for the BDD style use of the library
When these assertions were introduced in 1af3c778914f044e601ecfaed7dcb070d301e53c, we overlooked the expectation property.
Add the missing `expectation` properties.
1. Observe tests passing
=> Add missing expectation property for resolves/rejects

package-lock.json, package.json
Upgrade `@sinonjs/samsam` to v5 in order to fix sinonjs/referee-sinon#83.
All three libraries have to be updated to consistently upgrade samsam.
@mroderick I guess this needs to be release as another major then, right?
3. `npm t`
4. Observe that tests are still passing.
=> Upgrade formatio to v5, samsam to v5 and sinon to v9

lib/assertions/equals.js
Fix issue #184 by updating the assert.equals error message when using `undefined` as the expectation value.
2. Check that the updated message text looks good (this PR does not change any logic)
- [X ] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).
=> Fix assert.equals referencing deprecated assert.defined

lib/assertions/exception.js, lib/assertions/exception.test.js
The documentation claims that any object used to verify `assert.exception` calls is passed to the `match` API for assertion. In case that fails, we iterate over the properties of the object to check for non-matching properties. In case of a regular expression that fails the test, there are no own properties to iterate and tests always complete without error, even if the regexp does not match.
The solution is to check if at least one property was iterated.
I also had to add another test to verify the `else` case of the `hasOwnProperty` check for coverage.
3. `npm t`
=> Fix using a regexp matcher to assert exceptions

lib/assert-equals-host-objects.test.js, lib/assert.test.js, lib/custom-assertions.test.js, lib/expect.test.js, lib/referee.js, lib/referee.test.js, lib/refute.test.js, lib/test-helper/index.js, package-lock.json, package.json
Replaces an unmaintained custom event emitter with Node's built in one.
[bane](https://www.npmjs.com/package/bane) is an event emitter, which has had its last release 5 years ago. The API is roughly the same as Node's built-in event emitter, although in Node there's some things missing, e.g. the `off()` without any parameters is only available as `removeAllListeners`.
I'm not sure if this is meant to be used in the browser (although the download count is small enough to maybe not be too concerned about it)? I suppose in 2020, using it in the browser means using a bundler anyways. The available `npm run build` script seems to no longer work on `master`, so I didn't go further than that, but I do believe rollup is able to import node's internals in some form? (via plugin?)
This replaces …
=> Remove dependency on bane

lib/assertions/is-undefined.test.js, lib/interpolate-pos-arg.js
Fix issue #148 by providing an alternative stringification method for cases where the object prototype is not available.
If an object is created without a prototype and thus lacks `toString()`, assertions on the object will crash because the error message interpolation method expects this to be present. 
Check if the object has a `toString()` method, and stringify using `String(value)` if present. If not, use `JSON.stringify(value)`. This was one of the solutions proposed in the ticket; the other proposed solution was using `Object.prototype.toString.call(value)`, but this method caused existing tests to break.
3. `npm test` (unit test included in PR)
=> Properly stringify objects without prototype

lib/assertions/equals.js, lib/assertions/equals.test.js, lib/custom-assertions.test.js, lib/interpolate-properties.js
- Fixes double escaped newlines in `assert.equals`.
- Allows to skip escaping interpolated values by prefixing the property name with `!`, e.g. `some already ${formatted} value`.
When integrating the new formatting in referee with referee-sinon, most fake related assertion where serialized weirdly, mostly because referee-sinon already formats the values and referee's interpolation strategy would format and escape the whole string again.
With the new `!` notation for interpolated strings, custom assertions can opt out of referee's formatting.
3. `npm test`
=> String escapes

lib/assertions/rejects.js, lib/assertions/rejects.test.js, lib/assertions/resolves.js, lib/assertions/resolves.test.js, lib/create-async-assertion.js
- Add support for deep equality checks in `resolves` and `rejects` which also comes with support for matchers.
- Allow `resolves` and `rejects` to be called without an expectation (same as expectation being `samsam.match.any`).
These use cases are currently not supported or fail / succeed for the wrong reason:
```js
assert.resolves(promise, { some: 'object' })
assert.resolves(promise, match.string)
refute.resolves(promise, { some: 'object' })
refute.resolves(promise, match.string)
assert.rejects(promise, { some: 'object' })
assert.rejects(promise, match.string)
refute.rejects(promise, { some: 'object' })
refute.rejects(promise, match.string)
```
Furthermore, I'd like to verify that a given promise is either resolved or rejected, without caring for the value:
```js
assert.resolves(promise) …
```
=> Use deep equal comparison for resolves and rejects and allow to be called without expectation

lib/assertions/class-name.js, lib/assertions/contains.js, lib/expect.js, package-lock.json, package.json
This PR removes polyfills that have been obviated by `referee@8.0.0`, where we dropped support for legacy runtimes.
3. `npm test`
4. Observe that all tests pass
=> Remove obviated deps

lib/assertions/rejects.test.js, lib/assertions/resolves.test.js, lib/create-async-assertion.js, lib/create-async-assertion.test.js
Make second argument to `assert.resolves` and `assert.rejects` optional by setting the function arity to 1.
The change suggested in #115 to make the second argument for `assert.resolves` and `assert.rejects` optional was implemented as part of #214. However, as noticed in #219 the function arity isn't correct and therefore an exception is thrown when attempting to call these assertions with just one argument.
Fixed #219 
3. `npm test`
=> Fix resolves and rejects arity

docs/index.md
Typo fix in isUndefined
https://sinonjs.github.io/referee/#isundefined
1. Install mkdocs
2. mkdocs serve
3. Go to http://127.0.0.1:8000/#isundefined
=> Fix typo in isUndefined docs

.circleci/config.yml, lib/assertions/is-intl-collator.test.js, lib/assertions/is-intl-date-time-format.test.js, lib/assertions/is-intl-number-format.test.js
This PR adds support for Node 16
Sinon's pledge is to support all LTS Node versions, so we need to also run the tests in Node 16
* Fix tests that were failing in Node 16
* Run tests in CI in Node 16
1. Observe that CI runs tests in Node 16
2. Observe that CI still runs tests in Node 12 and 14
=> Add support for Node 16

lib/assertions/is-float-32-array.test.js, lib/assertions/is-float-64-array.test.js, lib/assertions/is-int-16-array.test.js, lib/assertions/is-int-32-array.test.js, lib/assertions/is-int-8-array.test.js, lib/assertions/is-u-int-16-array.test.js, lib/assertions/is-u-int-32-array.test.js, lib/assertions/is-u-int-8-array.test.js
Some tests were failing in node 12.14.1, because of changes (likely
improvements) to object formatting. By using `util.inspect` in tests, we
can match the strings correctly, no matter the node version.
1. `git checkout fde76f796baddf2d48edaffed835a0cb966b99ef` (current `master`)
2. `nvm install 12.14.1`
3. `npm ci`
4. `npm test`
5. Observe failing tests
6. Check out this branch
2. `nvm install 12.14.1`
3. `npm ci`
4. `npm test`
5. Observe no failing tests
=> Fix tests in node 12.14.1

lib/create-async-assertion.js, lib/create-async-assertion.test.js
If an exception is thrown in one of the async assertion callbacks, the corresponding promise wasn't resolved. A test case awaiting the promise would hang and timeout.
Example:
```js
const { assert, match } = require('@sinonjs/referee');
describe('test', () => {
it('hangs', async () => {
const promise = Promise.resolve('test');
const matcher = match(() => {
throw new Error('Ouch!');
});
await assert.resolves(promise, matcher);
});
});
```
Fail the test with the thrown error message by rejecting the internal assertion promise. Without handling the exception, the assertion promise wouldn't be resolved or rejected and a test case awaiting the promise would hang.
0. Run the above example with mocha and verify that the test case times out.
3. `npm test` …
=> Fix pending promise in async assertion on error

.github/workflows/main.yml
This PR improves the GitHub Actions workflow to check if `package-lock.json` has the expected `lockfileVersion` value (spoiler: `2`).
In #236 I managed to overwrite `package-lock.json` with a file using the old schema. So I had to revert that, and make another PR.
That just makes for a messy git history.
See https://github.com/mansona/npm-lockfile-version
1. Observe that the `static-analysis` check fails for this branch
2. Delete the `DELETE ME` commit and force push the changes
3. Observe that the `static-analysis` check passes for this branch
=> Verify lockfile version

.github/workflows/main.yml, lib/assertions/exception.js, lib/assertions/less.test.js, lib/assertions/same.test.js, lib/define-assertion/interpolate-properties.js, package-lock.json, package.json
Referee referred to an outdated version of `@sinonjs/samsam` causing the library to exist twice in the dependency tree when depending on `sinon` as well (e.g. `@sinonjs/referee-sinon`).
Since this will be released as a breaking change, I also made the following changes:
- Removed support for node 12, added node 18.
- Upgrades `devDependencies` and applies new prettier formatting.
3. `npm run lint`
4. `npm run prettier:check`
5. `npm test`
=> Upgrade samsam and dependency maintenance

package-lock.json, package.json
This fixes `npm run build`.
With the outdates version of `rebuild`, running `npm run build` failed with
```
> @sinonjs/referee@10.0.0 build:bundle                                                                                                                                                                                                                                             
> esbuild lib/referee.js --bundle --outfile=dist/referee.js                                                                                                                                                                                                                        
/Users/max/projects/sinon/referee/node_modules/esbuild/bin/esbuild:2 …
```
=> Upgrade esbuild to fix the build

.github/workflows/main.yml
This PR does a bit of housekeeping to the GitHub Actions workflow:
1. Update `actions/checkout` to latest
2. Prefer `cache` instruction of `actions/setup-node@v4` over `actions/cache`
=> Workflow housekeeping
